### ISSUE TITLE
cy.get use id if available

### ISSUE THREAD

**Issue by burner** [FDMediagroep/fd-cypress-recorder#27]
IMHO it would make tests less brittle if cy.get would use element ids where available.

accesses such as
```js
    cy.get(':nth-child(1) > :nth-child(1) > :nth-child(1) > div > input').type('foo@bar.com');
```  

might fail easily when layout changes.

```js
    cy.get('#emailInput').type('foo@bar.com');

```

might be better

**Comment by willemliu** [comment]
@burner that's a good suggestion. I have a use-case for the first but I will work on adding the option to use Id's in the context menu.

**Comment by burner** [comment]
@willemliu okay, having used a version with ID preference for a day, I can't really see any reason why that should not be the default.
Maybe I would be an idea to consider to have by ID be the default and adding new option to the context to "get by" current way.

**Comment by willemliu** [comment]
@burner the reason for us is because we want to be able to test any element on our page and check it's `value` (inner text or attributes). However we rarely have Id's on our elements. We also don't set Id's on the elements just for the purpose of writing tests.
Reading this article: https://blog.sapegin.me/all/react-testing-3-jest-and-react-testing-library/
has also given me insights as to what manner of selectors would work better for these kind of tests. So we'll think about how to incorporate the best options mentioned there.

**Comment by burner** [comment]
fair enough, so this change IMHO this PR already does what you ask.
If no ID is present it uses the current way. If an ID is present it uses that.
No IDs no change.

**Comment by willemliu** [comment]
@burner indeed. I totally missed the PR :scream:! My apologies for that. I'm going to review and do some testing with your PR and when everythings seems OK I'll put out a new release. Thanks for your input!

**Comment by burner** [comment]
@willemliu no worries, thats what the comment section is for. Thanks for caring
